const data = [
  {
    id: 1,
    imgSrc: `src/images/White and Black Lines Minimalist Typography Book Cover.jpg`,
    title: "Introspect",
    author: "Richard Sanchez",
    price: "$6.99",
    description:
      "A book about introspection, Sanchez goes into detail about how to introspect and how to use introspection to improve your life.",
  },
  {
    id: 2,
    imgSrc: "src/images/White Minimalist Sci-Fi Book Cover.jpg",
    title: "Am I A Robot?",
    author: "John Davies",
    price: "$4.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 3,
    imgSrc: "src/images/Pink and White Modern Design Book Cover.jpg",
    title: "Will It Ever Be Enough?",
    author: "Estelle Darcy",
    price: "$5.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 4,
    imgSrc: "src/images/Black & Yellow Modern Architecture Book Cover.jpg",
    title: "The Art Of Epic Structures",
    author: "Christian A. Jones",
    price: "$19.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 5,
    imgSrc: "src/images/Black and Red Typography Book Cover.jpg",
    title: "The Tale Of The Mistaken Twin",
    author: "Katie Thompson",
    price: "$5.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 6,
    imgSrc: "src/images/Black And White  Modern Alone Story Book Cover.jpg",
    title: "Alone: A True Story",
    author: "Morgan Maxwell",
    price: "$4.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 7,
    imgSrc: "src/images/Blue Simple Motivation Book Cover.jpg",
    title: "You Got This",
    author: "Benjamin Shah",
    price: "$4.55",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 8,
    imgSrc:
      "src/images/Coral and Monaco Blue Brush Strokes Creative Book Cover.jpg",
    title: "Path To Creative Freedom",
    author: "Takehiro Kanegi",
    price: "$4.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 9,
    imgSrc: "src/images/Orange and White Ink Typography Book Cover.jpg",
    title: "Write It Right",
    author: "Annie Okuda",
    price: "$5.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 10,
    imgSrc: "src/images/Purple and Red Illustrated Book Creator Cover.jpg",
    title: "Amara The Brave",
    author: "Matt Zhang",
    price: "$3.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 11,
    imgSrc: "src/images/Purple Illustrated Angry Robot Book Cover.jpg",
    title: "Angry Robot",
    author: "Brigette Schwartz",
    price: "$14.99",
    description: "Get your hands on this amazing book today",
  },
  {
    id: 12,
    imgSrc: "src/images/Red Self Help Bold Title Book Cover.jpg",
    title: "How To Build Your Self-Esteem",
    author: "Olivia Watson",
    price: "$9.99",
    description: "Get your hands on this amazing book today",
  },
];

export default data;
